### ISSUE TITLE
Queries for categories of drug-related charges

### ISSUE THREAD

**Issue by ghing** [sc3/cook-convictions-data#9]
@Yana715 defined some categories of drug-related charges.

~~She imagines that they'll be used to generate a pie chart.~~

**Manufacture/delivery generally of drugs that are not cannabis**

With that we can have possession of different amounts such as from 0-15, 15-100 etc. 
- MFG/DEL 01-15 GR COCAINE/ANLG
- MFG/DEL 1-14 GR HEROIN/ANALOG
- MFG/DEL 1-14 GR HEROIN/ANALOG
- MFG/DEL 01-15 GR COCAINE/ANLG
- MFG/DEL 15<100 GR COCA/ANALOG
- MFG/DEL 15<100 GR HEROIN/ANLG
- MFG/DEL 15<100 GR COCA/ANALOG

Dealing in a school area can also be included in this group, which I expect will make up the majority of offenses
- MFG/DEL COCAINE/SCH/PUB HS/PK
- MFG/DEL HEROIN/SCH/PUB HS/PK
- AMT NARC SCHED I/II/SCH/HS/PK

**Cannabis-related offenses**
- MFG/DEL CAN 2.5<10 GRAMS/SCH
- MFG/DEL CANNABIS/10-30 GRAMS
- MFG/DEL CANNABIS/30-500 GRAMS
- POSS CANNABIS/30-500 GRAM/1ST
- POSS AMT CON SUB EXCEPT(A
- POSS AMT CON SUB EXCEPT(A)/(D)

**Possession related-offenses**
- OTHER AMT NARCOTIC SCHED
- OTHER AMT NARCOTIC SCHED I&II
- POSS AMT CON SUB EXCEPT(A
- POSS AMT CON SUB EXCEPT(A)/(D)
- POSS AMT CON SUB EXCEPT(A
- OTHER AMT NARCOTIC SCHED I&II
- POSS AMT CON SUB EXCEPT(A)/(D)

Possible outliers to consider after determining the amount: Criminal drug conspiracy

**Update**

There are more charge descriptions than the one above.  We'll need to
- [ ]  Develop a comprehensive list of charge descriptions
- [ ]  Send Yana a list of charge descriptions that are _not_ drug-related for her to sanity check to make sure we haven't missed any.

**Comment by ghing** [comment]
@Yana715, I copied and pasted these lists of charge descriptions from your email and I noticed that there were some duplicates in each category.  Are there duplicates or is there some subtle difference between the charge descriptions that I'm missing.

**Comment by ghing** [comment]
I looked over the data with @Yana715 and found that the multiples that I [mentioned earlier](https://github.com/sc3/cook-convictions-data/issues/9#issuecomment-52736245) were not a result of sloppy copy and pasting but due to differences in whitespace.  Additionally, there are other variants in the charges that Yana didn't include in her list that I'll need to include.

**Comment by ghing** [comment]
@Yana715 

I had a couple of questions:
- What was your rationale for breaking out the charges related to possession/dealing near schools?
- (How) should we include convictions related to drugs in a penal institution in our drug breakdowns?  The law is in a different section of the law (ILCS 720-5/31A-1.1) than most of the other charges (ILCS 720-550, 720-570)?
- (How) should we include convictions related to drug parphenalia.  These are under ILCS 720-600.
- How do we categorize drug trafficking charges?

**Comment by Yana715** [comment]
Merci for the questions, I'll take a look and answer these tonight.

On Wed, Aug 27, 2014 at 11:36 AM, Geoffrey Hing notifications@github.com
wrote:

> @Yana715 https://github.com/Yana715
> 
> I had a couple of questions:
> - What was your rationale for breaking out the charges related to
>   possession/dealing near schools?
> - (How) should we include convictions related to drugs in a penal
>   institution in our drug breakdowns? The law is in a different section of
>   the law (ILCS 720-5/31A-1.1) than most of the other charges (ILCS 720-550,
>   720-570)?
> - (How) should we include convictions related to drug parphenalia.
>   These are under ILCS 720-600.
> - How do we categorize drug trafficking charges?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sc3/cook-convictions-data/issues/9#issuecomment-53601888
> .

## 

Yana Kunichoff

Independent journalist
yanakunichoff@gmail.com
832-551-6330
@yanazure

**Comment by Yana715** [comment]
- Since most of the school related charges are manufacturing or delivery,
  it's hard to put them into our amount-based analysis for the third graph
  dealing with manufacture/delivery. For that reason, even if the amount
  isn't substantial, it's most accurate to note them independently from the
  regular m/d charges that have amounts. However, we may want to discuss
  including them in a larger 'miscellaneous' section of the bar graph.
- How substantive are the convictions related to drugs in a penal
  institution? And do they have amounts? If there are very few, I would be
  fine including them in the 'miscellaneous' section, as long as we note that
  they are one of the charges included there.
- Can you send me what the charge description is for the paraphernalia?
  That may need to be separate, or again in the 'miscellaneous' if it's not a
  substantial percentage of the charges
- So this means drug trafficking is noted as separate from m/d? Like
  criminal drug conspiracy (another outlier), this seems substantially
  different from dealing in a school area, but I think we should check if the
  charge carries a particularly high penalty, and how common it is. It may
  not make sense for it to have it's own section in the bar graph if it's
  going to be so small as to be invisible.

On Wed, Aug 27, 2014 at 11:37 AM, Yana Kunichoff yanakunichoff@gmail.com
wrote:

> Merci for the questions, I'll take a look and answer these tonight.
> 
> On Wed, Aug 27, 2014 at 11:36 AM, Geoffrey Hing notifications@github.com
> wrote:
> 
> > @Yana715 https://github.com/Yana715
> > 
> > I had a couple of questions:
> > - What was your rationale for breaking out the charges related to
> >   possession/dealing near schools?
> > - (How) should we include convictions related to drugs in a penal
> >   institution in our drug breakdowns? The law is in a different section of
> >   the law (ILCS 720-5/31A-1.1) than most of the other charges (ILCS 720-550,
> >   720-570)?
> > - (How) should we include convictions related to drug parphenalia.
> >   These are under ILCS 720-600.
> > - How do we categorize drug trafficking charges?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/sc3/cook-convictions-data/issues/9#issuecomment-53601888
> > .
> 
> ## 
> 
> Yana Kunichoff
> 
> Independent journalist
> yanakunichoff@gmail.com
> 832-551-6330
> @yanazure

## 

Yana Kunichoff

Independent journalist
yanakunichoff@gmail.com
832-551-6330
@yanazure

**Comment by ghing** [comment]
> How substantive are the convictions related to drugs in a penal institution? 

131

> And do they have amounts?

They don't seem to.  Here are the charge descriptions/statutes:

final_chrgdesc,final_statute
POSSESS CANNIBIS PENAL INST,720-5/31A-1.1(B)
POSS CONTROLLED SUB PENAL INST,720-5/31A-1.1(B)
EMP DEL CON SUB/PENAL INST,720-5/31A-1.2(C)
BRING CANNABIS IN A PENAL INST,720-5/31A-1.1(A)(1)
BRING/POSS/CANNABIS/PENAL INST,720-5/31A-1.1(e)
POSSESS CANNIBIS PENAL INST,720-5/31A-1.1(b)
ATTEMPT BRING CANN. IN A PENAL,720-5/8-4(720-5/31A-1.1(A)(1)
BRING CANNABIS IN A PENAL INST,720-5/31A-1.1(a)(1)
POSS CONTROLLED SUB PENAL INST,720-5/31A-1.1(b)
EMP BRING CANNABIS/PENAL INST,720-5/31A-1.2(a)
BRING/POSS/CON SUB/PENAL INST,720-5/31A-1.1(g)
POSSESS CANNIBIS PENAL IN,720-5/31A-1.1(B)
ATT CON BRG/CANNIBIS PENAL INS,720-5/8-4(A)720-5\8-2\31A-1.1-A2
BRING CON SUBSTANCE PENAL,720-5/31A-1.1(A)(1)
BRING CANNABIS IN A PENAL,720-5/31A-1.1(A)(1)
POSS CONTROLLED SUB PENAL,720-5/31A-1.1(B)
BRING CON SUBSTANCE PENAL INST,720-5/31A-1.1(a)(1)
POSS CANNABIS PENAL INST,720-5/31A-1.1 B I
POSS.CONT.SUBS.PENAL INST.,720-5/31A-1.1(A)
CON/BRG CANNIBIS PENAL INST,720-5/8-2(720-5/31A-1)(A)(2)
CON CAUSE/BRING CANNIBIS PENAL,720-5/8-2(720-5/31A-1.1(A)(2)
CAUSE BRG CANNABIS PENAL INST,720-5/8-2/31A-1.1-A2
CONTROLLED SUB INTO PENAL INST,720-5/31A-1.1(2)(g)
CAUSE/BRG CANNIBIS PENAL,720-5/31A-1.1(A)(2)

> Can you send me what the charge description is for the paraphernalia?

There are 14 convictions related ot paraphernalia.  The charge descriptions and statutes are:

POSSESS DRUG PARAPHERNALIA,720-600/3.5(a)
DRUG PARAPHERNALIA SALE,720-600/3(a)
DRUG PARAPHERNALIA SALE,720-600/3(A)
POSS OF PARAPHERNALIA,720-600/3.5
POSS.DRUG PARAPHERALIA,720-600/3.5

> I think we should check if the charge carries a particularly high penalty, and how common it is. There are only 3 convictions for some kind of drug trafficking.  Here are the statutes if you want to look them up.

CANNABIS TRAFFICKING,56.5-705.1-A
CANNABIS TRAFFICKING,720-550/5.1
CANNABIS TRAFFIC/2000-5000 GR,720-550/5.1(a)
CONTROLLED SUB TRAFFICKING,720-570/401.1(A)
CONTROLLED SUB TRAFFICKING,720-570/401.1(a)
CANNABIS TRAFFICKING>5000 GRAM,720-550/5.1(a)
